### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by oujl** [boyliang/Hijack_AMS_broadIntent#1]
hello .
when i build proxybinder.cpp to libmyso.so   i have got an error  : 
android_runtime/AndroidRuntime.h: No such file or directory

then i install NDK patch   https://github.com/boyliang/ndk-patch 

i copy the ndk-patch to $NDK_PATH/platforms/android-8/arch-arm
and add APP_PLATFORM := android-8 in Application.mk  

the compiler error  disappear   but  has link error : 

yhdeMac-mini:myso yh$ ndk-build
[armeabi-v7a] Compile++ thumb: myso <= proxybinder.cpp
[armeabi-v7a] StaticLibrary  : libstdc++.a
[armeabi-v7a] SharedLibrary  : libmyso.so
/Users/yh/work/adt/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi-v7a/objs/myso/proxybinder.o: in function Main():jni/proxybinder.cpp:66: error: undefined reference to 'android::defaultServiceManager()'
/Users/yh/work/adt/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi-v7a/objs/myso/proxybinder.o: in function Main():jni/proxybinder.cpp:72: error: undefined reference to 'android::String16::String16(char const_)'
/Users/yh/work/adt/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi-v7a/objs/myso/proxybinder.o: in function Main():/Users/yh/work/adt/android-ndk-r9d/platforms/android-8/arch-arm/usr/include/utils/StrongPointer.h:149: error: undefined reference to 'android::RefBase::decStrong(void const_) const'
/Users/yh/work/adt/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi-v7a/objs/myso/proxybinder.o: in function Main():jni/proxybinder.cpp:72: error: undefined reference to 'android::String16::~String16()'
/Users/yh/work/adt/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi-v7a/objs/myso/proxybinder.o: in function Main():/Users/yh/work/adt/android-ndk-r9d/platforms/android-8/arch-arm/usr/include/utils/StrongPointer.h:149: error: undefined reference to 'android::RefBase::decStrong(void const_) const'
/Users/yh/work/adt/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: ./obj/local/armeabi-v7a/objs/myso/proxybinder.o: in function Main():jni/proxybinder.cpp:77: error: undefined reference to 'android::AndroidRuntime::mJavaVM'
collect2: ld returned 1 exit status
make: *_\* [obj/local/armeabi-v7a/libmyso.so] Error 1

it likes  the libs for ndk_patch has not loaded .  how can fix it .  ?  
tks!

**Comment by oujl** [comment]
i fix it  .it's my problem  
add  below code in android.mk

```
LOCAL_LDLIBS := -L$(SYSROOT)/usr/lib -llog
LOCAL_LDLIBS += -L$(SYSROOT)/usr/lib -landroid_runtime
LOCAL_LDLIBS += -L$(SYSROOT)/usr/lib -lbinder
LOCAL_LDLIBS += -L$(SYSROOT)/usr/lib -lcutils
LOCAL_LDLIBS += -L$(SYSROOT)/usr/lib -lutils
LOCAL_LDLIBS += -L$(SYSROOT)/usr/lib -lnativehelper 
```

**Comment by VishwanathPatil** [comment]
LOCAL_LDLIBS += -L$(SYSROOT)/usr/lib -lutils // this alone is sufficient
